server {
    listen 80;
    server_name henry.bmp.com.ng;

    root /var/www/html;  # The directory you want to point to
    index index.html index.htm;

    # Log files (Optional)
    access_log /var/log/nginx/henry.bmp.com.ng.access.log;
    error_log /var/log/nginx/henry.bmp.com.ng.error.log;

    location / {
        try_files $uri $uri/ =404;
    }
}